import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moon Palace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Seja bem-vindo(a) à minha biblioteca pessoal!
        </h1>

        <p className={styles.description}>
          (( Alguma descrição ))
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Cartão 1 &rarr;</h2>
            <p>Descrição do Cartão 1.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Cartão 2 &rarr;</h2>
            <p>Descrição do Cartão 2.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Cartão 3 &rarr;</h2>
            <p>Descrição do Cartão 3.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Cartão 4 &rarr;</h2>
            <p>Descrição do Cartão 4.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
